fieldLayouts:
  51f5b09d-a820-4e2a-9367-2cb1f13f6f3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8d2ee940-2eba-4141-9dda-82288d99eb01 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 195ef34c-7472-4f8c-9a81-83f923d77faf
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 85134406-d742-4d71-8245-556c13f1574f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c50e71d2-363e-4e98-b4d8-75c91be685c0 # Short Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9940c8f0-d176-4e27-8238-f2668e20f61d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d9dd4ea9-1687-4f88-81c1-aaabd2daf761 # Intro
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02ef290a-bc80-4b7e-9cb4-f71cf59d6314
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8830f2a6-b3db-4b49-9842-13a44ae5491e # project body
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 032b35f2-ad4a-47b8-aeee-30a27cdd3c28
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 3d9fea44-b0ae-4628-96dd-1f94e965888a
        userCondition: null
handle: default
hasTitleField: true
name: 'Par défaut'
section: 6aafa194-7f45-473e-b720-51bcc8fe547e # Projects
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
