fieldLayouts:
  79e3dffa-93ec-4b2e-b193-562f8614bac5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1b2ec53d-ced1-495c-a37c-244dc73b988d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c1afffb-baad-4cc8-bf26-df61e4cfe663
        userCondition: null
fs: bannersImages
handle: bannerImages
name: 'Banners Images'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
