fieldLayouts:
  e337ae4e-56a8-4f8b-9b8b-46e1d9ff7f86:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8748dd5c-437c-4bd1-9d2f-c8ed40e27c2c
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: d722e1ea-cec2-4299-a6ad-45cfea7cb97b
        userCondition: null
fs: generalDocuments
handle: generalDocs
name: 'General Documents'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
