fieldLayouts:
  c225e14d-4117-4630-92cd-ba8918349636:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8bc22b50-fa36-4752-be8b-d0d63ceb0147
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 36eaef52-ea0d-4f6f-bcc2-4cce75e97413
        userCondition: null
fs: projectsImages
handle: projectsImages
name: 'Projects Images'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
