columnSuffix: nlnjtzlk
contentColumnType: string(48)
fieldGroup: 086529c0-74a3-4c9e-ab52-0485965c1095 # globals
handle: addressNumber
instructions: null
name: Number
searchable: false
settings:
  byteLimit: null
  charLimit: 12
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
