columnSuffix: lntwkxxj
contentColumnType: string(128)
fieldGroup: c35f1271-3443-46b5-8ea6-da21707ff837 # homepage
handle: homepageProjectsTitle
instructions: null
name: Title
searchable: false
settings:
  byteLimit: null
  charLimit: 32
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
