columnSuffix: kgpyhitv
contentColumnType: string(64)
fieldGroup: d455c486-17de-49b7-acf3-ada7205ba599 # mainnav
handle: navLabel
instructions: 'Le texte de l''élément de navigation'
name: label
searchable: false
settings:
  byteLimit: null
  charLimit: 16
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
