columnSuffix: kkqyrxfl
contentColumnType: string(128)
fieldGroup: 086529c0-74a3-4c9e-ab52-0485965c1095 # globals
handle: phoneDisplay
instructions: 'Le numéro de téléphone tel que vous le voulez affiché à l''écran (pour les humains) ex: +32 2 345 678'
name: 'Phone Display'
searchable: false
settings:
  byteLimit: null
  charLimit: 32
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
