columnSuffix: lztlacvb
contentColumnType: string(256)
fieldGroup: ff26caa9-dbab-4514-b242-b2284d2d27df # projects
handle: projectShortDescription
instructions: null
name: 'Short Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 64
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
