defaultPlacement: end
enableVersioning: true
handle: homePage
name: 'Home page'
propagationMethod: all
siteSettings:
  bdc6cd0e-2a3a-4102-b579-2affcb3e3bff: # Zodiak Craft
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
